# SITE CONFIGURATION
title: DataDog # your site title
author: Juan Carlos Gonz치lez # You :P
description: > # Meta description of Homepage
  Blog personal, con informaci칩n acerca de temas como ciencia de datos, desarrollo, etc.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://datadogmx.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Juan Carlos Gonz치lez
  links:
    - https://twitter.com/jcarlosgzls
    - https://www.facebook.com/juancarlos.gonzalezaguilar.10
    - https://www.linkedin.com/in/juancarlosgonzalezaguilar
    - https://github.com/datadogmx 

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Blog personal, con informaci칩n acerca de temas como ciencia de datos, analisis de algoritmos, desarrollo, etc.


hero_img: posts/ocean_lg.png # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: carlosgonzagular@gmail.com # email for form submission

twitter_username: jcarlosgzls # replace with your_twitter_username or comment to remove link from footer
github_username:  datadogmx # replace with your_github_username or comment to remove link from footer
instagram_username: juancarlos.tar.gz # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: datadogmx   # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
remote_theme: "datadogmx/sleek" # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
